name: 'test action'

on: push

jobs:
  hello:
    runs-on: ubuntu-20.04
    name: Check
    steps:
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_TEST_API_KEY: 'hellalloa'
          ENV_ANOTHER_KEY: 'alloooo'

#      - name: Make envfile
#        uses: codex-team/action-create-env@v1.1
#        with:
#          envkey_VUE_APP_API_URL: 'privet'
#          envkey_VUE_APP_AUTH_TOKEN: 'token'

      - name: ls
        run: ls -la

      - name: show env
        run: cat .env
