name: Tick Local

on:
  schedule:
    - cron: '55 10 * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Send a notification
    steps:
      - name: Send a message
        uses: codex-team/action-codexbot-notify@v1
        with:
          webhook: ${{ secrets.CODEX_BOT_CHAT }}
          message: '⏰ It is 10:55 UTC+3!'
          parse_mode: 'markdown'
          disable_web_page_preview: true